# Generated by Django 5.2.5 on 2025-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('icon', models.CharField(default='film', help_text='Например: dumbbell, running, heart-pulse, yoga, fire', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('color', models.CharField(default='bg-gradient-to-br from-purple-600 to-pink-600', max_length=30, verbose_name='Цвет (Tailwind)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.category', verbose_name='Категории'),
        ),
    ]
