# Generated by Django 5.2.5 on 2025-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='bg-gradient-to-br from-purple-600 to-pink-600', max_length=300, verbose_name='Цвет (Tailwind)'),
        ),
    ]
